name: weatherly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  intl: ^0.20.2
  get_it: ^8.0.3
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  flutter_svg: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  riverpod_annotation: ^2.6.1
  internet_connection_checker_plus: ^2.7.2
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.12
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  icons_launcher: ^3.0.1
  riverpod_generator: ^2.4.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/myJson/
    - assets/svg/
    - assets/
    - env.json

