// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class Sys {
// /*
// {
//   "pod": "d"
// }
// */

//   String? pod;

//   Sys({
//     this.pod,
//   });
//   Sys.fromJson(Map<String, dynamic> json) {
//     pod = json['pod']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['pod'] = pod;
//     return data;
//   }
// }

// class Rain {
// /*
// {
//   "3h": 0.26
// }
// */

//   double? the3h;

//   Rain({
//     this.the3h,
//   });
//   Rain.fromJson(Map<String, dynamic> json) {
//     the3h = json['3h']?.toDouble();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['3h'] = the3h;
//     return data;
//   }
// }

// class Wind {
// /*
// {
//   "speed": 0.62,
//   "deg": 349,
//   "gust": 1.18
// }
// */

//   double? speed;
//   int? deg;
//   double? gust;

//   Wind({
//     this.speed,
//     this.deg,
//     this.gust,
//   });
//   Wind.fromJson(Map<String, dynamic> json) {
//     speed = json['speed']?.toDouble();
//     deg = json['deg']?.toInt();
//     gust = json['gust']?.toDouble();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['speed'] = speed;
//     data['deg'] = deg;
//     data['gust'] = gust;
//     return data;
//   }
// }

// class Clouds {
// /*
// {
//   "all": 100
// }
// */

//   int? all;

//   Clouds({
//     this.all,
//   });
//   Clouds.fromJson(Map<String, dynamic> json) {
//     all = json['all']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['all'] = all;
//     return data;
//   }
// }

// class Weather {
// /*
// {
//   "id": 500,
//   "main": "Rain",
//   "description": "light rain",
//   "icon": "10d"
// }
// */

//   int? id;
//   String? main;
//   String? description;
//   String? icon;

//   Weather({
//     this.id,
//     this.main,
//     this.description,
//     this.icon,
//   });
//   Weather.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     main = json['main']?.toString();
//     description = json['description']?.toString();
//     icon = json['icon']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['main'] = main;
//     data['description'] = description;
//     data['icon'] = icon;
//     return data;
//   }
// }

// class Main {
// /*
// {
//   "temp": 296.76,
//   "feels_like": 296.98,
//   "temp_min": 296.76,
//   "temp_max": 297.87,
//   "pressure": 1015,
//   "sea_level": 1015,
//   "grnd_level": 933,
//   "humidity": 69,
//   "temp_kf": -1.11
// }
// */

//   double? temp;
//   double? feelsLike;
//   double? tempMin;
//   double? tempMax;
//   int? pressure;
//   int? seaLevel;
//   int? grndLevel;
//   int? humidity;
//   double? tempKf;

//   Main({
//     this.temp,
//     this.feelsLike,
//     this.tempMin,
//     this.tempMax,
//     this.pressure,
//     this.seaLevel,
//     this.grndLevel,
//     this.humidity,
//     this.tempKf,
//   });
//   Main.fromJson(Map<String, dynamic> json) {
//     temp = json['temp']?.toDouble();
//     feelsLike = json['feels_like']?.toDouble();
//     tempMin = json['temp_min']?.toDouble();
//     tempMax = json['temp_max']?.toDouble();
//     pressure = json['pressure']?.toInt();
//     seaLevel = json['sea_level']?.toInt();
//     grndLevel = json['grnd_level']?.toInt();
//     humidity = json['humidity']?.toInt();
//     tempKf = json['temp_kf']?.toDouble();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['temp'] = temp;
//     data['feels_like'] = feelsLike;
//     data['temp_min'] = tempMin;
//     data['temp_max'] = tempMax;
//     data['pressure'] = pressure;
//     data['sea_level'] = seaLevel;
//     data['grnd_level'] = grndLevel;
//     data['humidity'] = humidity;
//     data['temp_kf'] = tempKf;
//     return data;
//   }
// }

// class ForecastModel {
// /*
// {
//   "dt": 1661871600,
//   "main": {
//     "temp": 296.76,
//     "feels_like": 296.98,
//     "temp_min": 296.76,
//     "temp_max": 297.87,
//     "pressure": 1015,
//     "sea_level": 1015,
//     "grnd_level": 933,
//     "humidity": 69,
//     "temp_kf": -1.11
//   },
//   "weather": [
//     {
//       "id": 500,
//       "main": "Rain",
//       "description": "light rain",
//       "icon": "10d"
//     }
//   ],
//   "clouds": {
//     "all": 100
//   },
//   "wind": {
//     "speed": 0.62,
//     "deg": 349,
//     "gust": 1.18
//   },
//   "visibility": 10000,
//   "pop": 0.32,
//   "rain": {
//     "3h": 0.26
//   },
//   "sys": {
//     "pod": "d"
//   },
//   "dt_txt": "2022-08-30 15:00:00"
// }
// */

//   int? dt;
//   Main? main;
//   List<Weather>? weather;
//   Clouds? clouds;
//   Wind? wind;
//   int? visibility;
//   double? pop;
//   Rain? rain;
//   Sys? sys;
//   String? dtTxt;

//   ForecastModel({
//     this.dt,
//     this.main,
//     this.weather,
//     this.clouds,
//     this.wind,
//     this.visibility,
//     this.pop,
//     this.rain,
//     this.sys,
//     this.dtTxt,
//   });
//   ForecastModel.fromJson(Map<String, dynamic> json) {
//     dt = json['dt']?.toInt();
//     main = (json['main'] != null) ? Main.fromJson(json['main']) : null;
//     if (json['weather'] != null) {
//       final v = json['weather'];
//       final arr0 = <Weather>[];
//       v.forEach((v) {
//         arr0.add(Weather.fromJson(v));
//       });
//       weather = (arr0.firstOrNull ?? []) as List<Weather>?;
//     }
//     clouds = (json['clouds'] != null) ? Clouds.fromJson(json['clouds']) : null;
//     wind = (json['wind'] != null) ? Wind.fromJson(json['wind']) : null;
//     visibility = json['visibility']?.toInt();
//     pop = json['pop']?.toDouble();
//     rain = (json['rain'] != null) ? Rain.fromJson(json['rain']) : null;
//     sys = (json['sys'] != null) ? Sys.fromJson(json['sys']) : null;
//     dtTxt = json['dt_txt']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['dt'] = dt;
//     if (main != null) {
//       data['main'] = main!.toJson();
//     }
//     if (weather != null) {
//       final v = weather;
//       final arr0 = [];
//       for (var v in v!) {
//         arr0.add(v.toJson());
//       }
//       data['weather'] = arr0;
//     }
//     if (clouds != null) {
//       data['clouds'] = clouds!.toJson();
//     }
//     if (wind != null) {
//       data['wind'] = wind!.toJson();
//     }
//     data['visibility'] = visibility;
//     data['pop'] = pop;
//     if (rain != null) {
//       data['rain'] = rain!.toJson();
//     }
//     if (sys != null) {
//       data['sys'] = sys!.toJson();
//     }
//     data['dt_txt'] = dtTxt;
//     return data;
//   }
// }

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ForecastModel {

  ForecastModel({
    this.temp,
    this.date,
    this.maxTemp,
    this.minTemp,
    this.main,
    this.icon,
  });
  ForecastModel.fromJson(Map<String, dynamic> json) {
    temp = json['temp']?.toString();
    date = json['date']?.toString();
    maxTemp = json['maxTemp']?.toString();
    minTemp = json['minTemp']?.toString();
    main = json['main']?.toString();
    icon = json['icon']?.toString();
  }
/*
{
  "temp": "temp",
  "date": "entry.key",
  "maxTemp": "",
  "minTemp": "minTemp",
  "main": "main",
  "icon": "icon"
} 
*/

  String? temp;
  String? date;
  String? maxTemp;
  String? minTemp;
  String? main;
  String? icon;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temp'] = temp;
    data['date'] = date;
    data['maxTemp'] = maxTemp;
    data['minTemp'] = minTemp;
    data['main'] = main;
    data['icon'] = icon;
    return data;
  }
}
